apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: onboarding
  title: Azure Onboarding - Mahes
  description: Onboard to Azure
  tags:
    - azure
spec:
  owner: Mahes
  type: service
  parameters:
    - title: You are about to request access to a shared team key/value store in Vault
      required:
        - azure_object_id
      properties:
        azure_object_id:
          title: Object ID for your team
          type: string
          description: The object ID for the group in Azure active directory that matches your team
  steps:
    - id: run-onboarding
      name: Run onboarding
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=backstage&owner=maheswaran-hub'
        workflowId: 'hello.yaml'
        branchOrTagName: 'main'
        workflowInputs:
          azure_object_id: ${{ parameters.azure_object_id }}
  output:
    links:
      - title: Check status of your onboarding at
        url: https://github.com/CloudSpotPL/backstage_playground/actions
