on:
  workflow_dispatch:
    inputs:
      azure_object_id:
        description: 'Azure AD group object ID'
        required: true
permissions:
  id-token: write
  contents: read

name: hello-world
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
